---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vtkhdiuf/public_html/
    - /bin/cp -rf app $DEPLOYPATH
    - /bin/cp -rf config $DEPLOYPATH
    - /bin/cp -rf database $DEPLOYPATH
    - /bin/cp -rf public $DEPLOYPATH
    - /bin/cp -rf resources $DEPLOYPATH
    - /bin/cp -rf routes $DEPLOYPATH
    - /bin/cp -rf storage $DEPLOYPATH
    - /bin/cp -rf vendor $DEPLOYPATH