@extends('frontend.templates.master')
@section('content')
    <br>
    <br>
    <br>
    <br>
    <br>
    @include('frontend.product.tool-box')
    @include('frontend.product.list-product')
@endsection
